### ISSUE TITLE
Contact Method?

### ISSUE THREAD

**Issue by Boso101** [exmex/HS_Multilang#1]
Hi just recently stumbbled upon this, do you happen to have discord or any social media? I want some help actually getting a start on this and I have no clue what to do. and what unity build is best for this because ive noticed 2 branches atm

**Comment by exmex** [comment]
EDIT:
Oh you mean If I have some kind of contact method lol. You can open issues if something isn't working quite right. And for questions just ask away here^^


-----
18ef2ca4e3277d10ab0d59c2c7e5eab834e6ec76 This says what Unity version is required.

The other branch is 7711aa9ec487fb8c22b3298e8934aff52ddf1118 "Updated to Unity 2017" where I updated it to the "newest" version of unity and re-written (ONLY THE LOGIN PART ATM) from NGUI to UnityUI. (Remember though this version is not tested.)

EDIT:
You can see the difference in these images:
Old:
![](https://camo.githubusercontent.com/4f7a9631a3548dda927d9a67ce787200b7d69e37/687474703a2f2f692e696d6775722e636f6d2f454a5353356e362e706e67)

New:
![](https://user-images.githubusercontent.com/5639139/37568636-3b5e772a-2ad8-11e8-906f-f389b4f37283.png)

**Comment by Boso101** [comment]
Thanks. But I need help making a start. I simply don’t know what I should be doing, and is it even capable of playing a game atm? I just don’t know what to do as a starting point

**Comment by exmex** [comment]
The master branch works yes. The unityui branch could work, although after upgrading to Unity2017 I didn't test it.
About the starting part.. If you don't know unity / never used it before, I'd suggest learning how unity works. If you've already worked with unity and know how it works, you could just go read the code ;)

**Comment by Boso101** [comment]
Okay well had a look through all the scripts because I cant seem to find which script controls the starting gold. I am also building the project without the login scene so idk if that is fine or not. But yeah I have had no luck setting the starting Gold to buy packs

**Comment by exmex** [comment]
As you can see in this file:
https://github.com/exmex/HS_Multilang/blob/18ef2ca4e3277d10ab0d59c2c7e5eab834e6ec76/Assets/Scripts/web.cs

Everthing is handled by a Webserver backend.

What you're looking for is this:
https://github.com/exmex/HS_Multilang/blob/18ef2ca4e3277d10ab0d59c2c7e5eab834e6ec76/Assets/Scripts/web.cs#L158

If you've read the README.md you would've known. This is the login.php:
```php
<?php
echo "ok";
echo "/1";  // Id
echo "/ExMex"; // Nickname
echo "/100"; // Expack
echo "/1000"; // Gold

// Card items
echo "/id1";
echo "/id2";
echo "/id3";
echo "/id4";
?>
```

**Comment by Boso101** [comment]
yeahh no clue what to do... I put the login.php on xamp, but I get this when attempting to register

![image](https://user-images.githubusercontent.com/22697660/38762874-4bd5b976-3fd0-11e8-93ab-34af4ade3215.png)

**Comment by exmex** [comment]
Yeah because you didn't create the register script. Also explained in the README.. Please learn to understand the code first. You could've easily traced that issue through the code to the web.cs. And the web.cs has more scripts apart from the login.php Which you've to create. For example this one:
https://github.com/exmex/HS_Multilang/blob/dfa6496a810c78624ceadf5bf0360c3cd389f912/_API/getsets.php#L20
And lots more.

EDIT:
One more thing. You don't actually register. Since NOTHING gets saved anyway.

**Comment by Boso101** [comment]
Okay thanks for the help. Ill spend some time studying the code and working out how things work
